app = 'testcomments'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'
  context = "."

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "uploads_vol"
  destination = "/uploads"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024